# ==============================================================================
# File Name: touch_button.gd
# Path: res://scripts/touch/touch_button.gd
#
# Description:
#   One round on-screen action button. It does not read input itself: TouchControls routes
#   touches to it (so several fingers can work at once) and it only draws and reports.
#   The hit area is larger than the drawn circle so thumbs do not have to be precise.
#
#   Look (Purgatory brand, docs/UI_DESIGN_SYSTEM.md section 7): a blackened-iron disc (cached radial
#   gradient texture) with a brass/iron rim, a bone icon and ember accents. Tiers keep one component
#   family with a clear hierarchy: PRIMARY (attack: heaviest rim), COMBAT (kick, slide, block, burst),
#   CONTEXT (USE/OPEN: ember rim, the contextual primary), QUIET (pause, map: lower contrast).
#   Drawing is a handful of primitives and only happens when the state changes (plus the onboarding
#   pulse while a hint is highlighting a button).
# ==============================================================================
class_name TouchButton
extends Control

const HIT_SLOP := 1.30   # touch radius = drawn radius * this

enum Mode { HOLD, TOGGLE }
enum Tier { COMBAT, PRIMARY, CONTEXT, QUIET }

const RIM_SEGMENTS := 56
# Typography rule: short labels (USE / OPEN, the potion count) are Cinzel; PUI.MIN_DISPLAY_SIZE is the smallest caption.
const CAPTION_MIN_FS := PUI.MIN_DISPLAY_SIZE

# ── Button anatomy (fractions of the DRAWN radius r; every button uses the same anatomy at its own size) ──
# A physical control: a soft drop shadow, a thick aged-brass/iron BEZEL (the ring), a thin brighter brass HAIRLINE
# on the bezel's inner edge, a recessed blackened-iron FACE with an inner shadow line, and a bone ICON.
const RING_FRAC     := 0.22   # bezel thickness: 11% of the diameter (Pause/Map: RING_FRAC_QUIET)
const RING_FRAC_QUIET := 0.18
const HAIRLINE_FRAC := 0.03   # bright hairline on the bezel's inner edge (>= 1.5 px)
const ICON_FRAC     := 0.84   # icon radius as a fraction of the FACE radius (the icon art fills ~55% of the face diameter)
const SHADOW_DROP   := 0.07   # drop shadow offset (down), fraction of r
const SHADOW_DROP_DOWN := 0.03   # ... while pressed (the button sits lower, the shadow tightens)
const SHADOW_REACH  := 1.16   # drop shadow disc radius, fraction of r
const SHADOW_ALPHA  := 0.55   # peak alpha of the (cached, radial) shadow texture
const FACE_INSET_SHADOW := 0.07   # width of the dark inner shadow line under the bezel, fraction of r

var action    : String = ""
var icon_kind : String = ""
var label     : String = ""
var mode      : Mode   = Mode.HOLD
var tier      : Tier   = Tier.COMBAT
var radius    : float  = 80.0           # drawn radius, virtual px
var center    : Vector2 = Vector2.ZERO  # in TouchControls space
var pressed_visual : bool = false
var toggled_on     : bool = false
var cooldown       : float = 0.0        # 0..1 fraction remaining (ring over the button)
var badge          : String = ""        # small count in the corner (e.g. potions)
var highlighted    : bool = false       # onboarding pulse
var enabled_look   : bool = true
var unavailable    : bool = false       # drawn in the disabled look (e.g. the flask with no potions); input is unaffected

# Text metrics are cached: shaping a string on every pulse frame would be wasted work.
var _label_key : String = ""
var _label_size : Vector2 = Vector2.ZERO
var _badge_key : String = ""
var _badge_size : Vector2 = Vector2.ZERO
var _badge_fs : int = 14

static var _skin : Dictionary = {}


static func tier_for(p_action: String) -> Tier:
	match p_action:
		"attack": return Tier.PRIMARY
		"equip": return Tier.CONTEXT
		"ui_menu", "minimap": return Tier.QUIET
	return Tier.COMBAT


func setup(p_action: String, p_icon: String, p_mode: Mode = Mode.HOLD) -> void:
	action = p_action
	icon_kind = p_icon
	mode = p_mode
	tier = tier_for(p_action)
	mouse_filter = Control.MOUSE_FILTER_IGNORE   # touches are routed by TouchControls, not the GUI
	texture_filter = CanvasItem.TEXTURE_FILTER_LINEAR_WITH_MIPMAPS   # the baked art is drawn at many sizes


func place(p_center: Vector2, p_radius: float) -> void:
	center = p_center
	radius = p_radius
	position = center - Vector2(radius, radius) * HIT_SLOP
	size = Vector2(radius, radius) * 2.0 * HIT_SLOP
	queue_redraw()


func _process(_delta: float) -> void:
	if highlighted:
		queue_redraw()   # animate the onboarding pulse


func hit(p: Vector2) -> bool:
	return visible and p.distance_to(center) <= radius * HIT_SLOP


# ── Baked art (assets/touch/, generated by tools/make_control_art.gd) ─────────────────────────────────────────
# Rim + face bases (Attack has its own with four studs; every other round button shares the "sub" base) and icons,
# each baked per state because a tint cannot do it. Loaded once, cached; a missing file falls back to the
# code-drawn button below, so the layer can never be left without controls.
const ART_DIR := "res://assets/touch/"
const ART_STATES: Array[String] = ["default", "pressed", "cooldown", "disabled"]
const ART_ICONS := {"attack": "sword", "block": "shield", "kick": "boot", "burst": "flask", "slide": "chevrons", "use": "key"}
const ART_BASE_PX := {"attack": 512, "sub": 256}
const ART_ICON_PX := 256
const ART_CANVAS_HALF := 1.12   # base texture half-size = drawn radius * this (room for the pressed glow)
const ART_BEZEL := 0.22         # bezel thickness (fraction of r): the baked rim spans 0.80..1.00 of the disc
const ICON_TEX_FRAC := 1.15     # icon texture half-size as a fraction of the face radius

static var _art: Dictionary = {}


static func art_texture(art_name: String) -> Texture2D:
	if _art.has(art_name):
		return _art[art_name]
	var path: String = ART_DIR + art_name + ".png"
	var tex: Texture2D = null
	if ResourceLoader.exists(path):
		tex = load(path) as Texture2D
	_art[art_name] = tex
	return tex


## Every file name the baked controls reference (without folder / extension), for the asset test.
static func art_names() -> Array[String]:
	var out: Array[String] = []
	for st in ART_STATES:
		for b in ART_BASE_PX:
			out.append("base_%s_%s" % [b, st])
		for kind in ART_ICONS.values():
			out.append("icon_%s_%s" % [kind, st])
	return out


func art_state() -> String:
	if unavailable and not (pressed_visual or toggled_on):
		return "disabled"
	if pressed_visual or toggled_on:
		return "pressed"
	if cooldown > 0.0:
		return "cooldown"
	return "default"


func _base_art() -> Texture2D:
	if tier == Tier.QUIET:
		return null   # Pause / Map stay the quiet code-drawn members of the family
	return art_texture("base_%s_%s" % ["attack" if tier == Tier.PRIMARY else "sub", art_state()])


func _icon_art() -> Texture2D:
	if not ART_ICONS.has(icon_kind):
		return null
	return art_texture("icon_%s_%s" % [ART_ICONS[icon_kind], art_state()])


# ── Cached materials ──────────────────────────────────────────────────────────

## A round radial-gradient texture whose last stop is transparent, so the square texture reads as a disc.
## stops: [[offset, Color], ...] (the final stop should have alpha 0 at offset 1.0).
static func _radial(key: String, stops: Array, px: int) -> Texture2D:
	if _skin.has(key):
		return _skin[key]
	var g := Gradient.new()
	var offs := PackedFloat32Array()
	var cols := PackedColorArray()
	for s in stops:
		offs.append(float(s[0]))
		cols.append(s[1])
	g.offsets = offs
	g.colors = cols
	var t := GradientTexture2D.new()
	t.gradient = g
	t.fill = GradientTexture2D.FILL_RADIAL
	t.fill_from = Vector2(0.5, 0.5)
	t.fill_to = Vector2(1.0, 0.5)   # offset 1.0 is the disc edge
	t.width = px
	t.height = px
	_skin[key] = t
	return t


static func _clear(c: Color) -> Color:
	return Color(c.r, c.g, c.b, 0.0)


## Button face: a recessed disc of blackened iron, a touch lighter at the centre, darker toward the bezel (kept subtle:
## a well, not a glossy dome). down = pressed in: darker, with a faint ember warmth at the centre.
static func body_texture(p_tier: int, down: bool) -> Texture2D:
	var key := "body|%d|%s" % [p_tier, down]
	if _skin.has(key):
		return _skin[key]
	var hi: Color = PUI.IRON
	var mid: Color = PUI.IRON.lerp(PUI.IRON_DEEP, 0.55)
	var lo: Color = PUI.IRON_DEEP
	var a: float = 0.97
	match p_tier:
		Tier.PRIMARY:
			hi = PUI.IRON_RAISED.darkened(0.12)
		Tier.CONTEXT:
			hi = PUI.IRON.lerp(PUI.EMBER_DEEP, 0.16)
			mid = PUI.IRON_DEEP.lerp(PUI.EMBER_DEEP, 0.07)
		Tier.QUIET:
			hi = PUI.IRON.darkened(0.08)
			a = 0.90
	if down:
		hi = hi.darkened(0.30).lerp(PUI.EMBER_DEEP, 0.12)
		mid = mid.darkened(0.30)
		lo = lo.darkened(0.30)
	var edge := Color(lo.r, lo.g, lo.b, a)
	return _radial(key, [
		[0.0, Color(hi.r, hi.g, hi.b, a)],
		[0.66, Color(mid.r, mid.g, mid.b, a)],
		[0.97, edge],
		[1.0, _clear(edge)],
	], 128)


## Soft drop shadow: a dark disc fading to nothing at its edge. One cached texture for every button.
static func shadow_texture() -> Texture2D:
	return _radial("shadow", [
		[0.0, Color(0, 0, 0, SHADOW_ALPHA)],
		[0.70, Color(0, 0, 0, SHADOW_ALPHA * 0.72)],
		[1.0, Color(0, 0, 0, 0.0)],
	], 96)


## Joystick base: a dark well, a touch lighter toward its rim; the iron rim ring is drawn on top.
static func stick_base_texture() -> Texture2D:
	return _radial("stick_base", [
		[0.0, Color(PUI.VOID.r, PUI.VOID.g, PUI.VOID.b, 0.40)],
		[0.60, Color(PUI.IRON_DEEP.r, PUI.IRON_DEEP.g, PUI.IRON_DEEP.b, 0.52)],
		[0.96, Color(PUI.IRON.r, PUI.IRON.g, PUI.IRON.b, 0.66)],
		[1.0, _clear(PUI.IRON)],
	], 160)


## Joystick thumb: a polished bone / iron knob, lit from the centre.
static func stick_knob_texture() -> Texture2D:
	var bone: Color = PUI.BONE_DIM
	var rim: Color = PUI.EDGE_BRASS.darkened(0.35)
	return _radial("stick_knob", [
		[0.0, Color(bone.r, bone.g, bone.b, 0.96)],
		[0.55, Color(bone.darkened(0.30).r, bone.darkened(0.30).g, bone.darkened(0.30).b, 0.96)],
		[0.96, Color(rim.r, rim.g, rim.b, 0.96)],
		[1.0, _clear(rim)],
	], 96)


# ── Drawing ───────────────────────────────────────────────────────────────────

## Bezel colour: aged brass for the primary, iron-with-brass for the family, ember when held.
func _ring_color(down: bool) -> Color:
	if down:
		return PUI.EMBER if tier != Tier.QUIET else PUI.EMBER_DEEP
	match tier:
		Tier.PRIMARY: return PUI.EDGE_BRASS.darkened(0.30)
		Tier.CONTEXT: return PUI.EMBER_DEEP.darkened(0.15)
		Tier.QUIET:   return PUI.EDGE.darkened(0.10)
	return PUI.EDGE.lerp(PUI.EDGE_BRASS, 0.55)


func _draw() -> void:
	var base_tex: Texture2D = _base_art()
	var icon_tex: Texture2D = _icon_art()
	if base_tex != null and icon_tex != null:
		_draw_baked(base_tex, icon_tex)
		return
	_draw_coded()


## The baked-art button: cached drop shadow, the base (rim + face) and icon textures for the current state, then
## the code-drawn pieces that carry meaning on top (charge fill, cooldown, caption, count badge, pulse).
func _draw_baked(base_tex: Texture2D, icon_tex: Texture2D) -> void:
	var c: Vector2 = size * 0.5
	var r: float = radius
	var down: bool = pressed_visual or toggled_on
	var rw: float = r * ART_BEZEL
	var fr: float = r - rw

	var drop: float = r * (SHADOW_DROP_DOWN if down else SHADOW_DROP)
	var reach: float = r * SHADOW_REACH
	draw_texture_rect(shadow_texture(), Rect2(c + Vector2(0.0, drop) - Vector2(reach, reach), Vector2(reach, reach) * 2.0), false)
	var half: float = r * ART_CANVAS_HALF
	draw_texture_rect(base_tex, Rect2(c - Vector2(half, half), Vector2(half, half) * 2.0), false)
	if tier == Tier.CONTEXT and not down:
		draw_arc(c, r - rw - r * 0.03, 0.0, TAU, RIM_SEGMENTS, Color(PUI.EMBER.r, PUI.EMBER.g, PUI.EMBER.b, 0.85), maxf(r * 0.035, 2.0), true)   # contextual: an ember ring

	if highlighted:
		var t: float = fmod(Time.get_ticks_msec() * 0.001, 1.2) / 1.2
		draw_arc(c, r * (1.05 + 0.30 * t), 0.0, TAU, RIM_SEGMENTS, Color(PUI.EMBER_BRIGHT.r, PUI.EMBER_BRIGHT.g, PUI.EMBER_BRIGHT.b, 1.0 - t), maxf(r * 0.07, 3.0), true)

	var ih: float = fr * ICON_TEX_FRAC
	var ic: Vector2 = c + Vector2(0.0, r * 0.03 if down else 0.0)
	draw_texture_rect(icon_tex, Rect2(ic - Vector2(ih, ih), Vector2(ih, ih) * 2.0), false)

	if cooldown > 0.0:
		var a0: float = -PI * 0.5
		var a1: float = a0 + TAU * clampf(cooldown, 0.0, 1.0)
		draw_arc(c, fr * 0.5, a0, a1, 32, Color(0.03, 0.02, 0.02, 0.50), fr, false)
		draw_arc(c, r - rw * 0.5, a0, a1, RIM_SEGMENTS, PUI.EMBER, rw * 0.5, true)

	if label != "":
		_draw_label(c, r)
	if badge != "":
		_draw_badge(c, r)


## The code-drawn fallback (and Pause / Map): the same anatomy built from primitives.
func _draw_coded() -> void:
	var c: Vector2 = size * 0.5
	var r: float = radius
	var down: bool = pressed_visual or toggled_on
	var quiet: bool = tier == Tier.QUIET
	var rw: float = maxf(r * (RING_FRAC_QUIET if quiet else RING_FRAC), 3.0)   # bezel thickness
	var fr: float = r - rw                                                      # face radius
	var ring: Color = _ring_color(down)
	var hair: float = maxf(r * HAIRLINE_FRAC, 1.5)

	# soft drop shadow: floats the button above the scene (smaller offset when pushed in)
	var drop: float = r * (SHADOW_DROP_DOWN if down else SHADOW_DROP)
	var reach: float = r * SHADOW_REACH
	draw_texture_rect(shadow_texture(), Rect2(c + Vector2(0.0, drop) - Vector2(reach, reach), Vector2(reach, reach) * 2.0), false)

	# bezel: dark contact edge, the thick ring, restrained lit / shaded arcs
	draw_arc(c, r - 0.75, 0.0, TAU, RIM_SEGMENTS, Color(0, 0, 0, 0.55), 1.5, true)
	draw_arc(c, r - rw * 0.5, 0.0, TAU, RIM_SEGMENTS, ring, rw - 1.0, true)
	if not quiet:
		draw_arc(c, r - rw * 0.30, PI * 1.05, PI * 1.60, 20, ring.lightened(0.30), rw * 0.26, true)   # lit upper-left
		draw_arc(c, r - rw * 0.72, PI * 0.05, PI * 0.62, 20, ring.darkened(0.40), rw * 0.30, true)    # shaded lower-right
	# recessed face
	draw_texture_rect(body_texture(tier, down), Rect2(c - Vector2(fr, fr) - Vector2(1, 1), Vector2(fr + 1.0, fr + 1.0) * 2.0), false)
	# hairline on the bezel's inner edge, then the inner shadow line it casts on the face
	var hair_col: Color = PUI.EMBER_BRIGHT if down else PUI.EDGE_BRASS.lightened(0.28)
	draw_arc(c, fr + hair * 0.5, 0.0, TAU, RIM_SEGMENTS, Color(hair_col.r, hair_col.g, hair_col.b, 0.85 if not quiet else 0.6), hair, true)
	var sh: float = maxf(r * FACE_INSET_SHADOW, 2.0)
	draw_arc(c, fr - sh * 0.5, PI * 0.85, PI * 1.95, 24, Color(0, 0, 0, 0.62 if down else 0.50), sh, true)   # upper-left: the bezel shades the well
	draw_arc(c, fr - sh * 0.3, PI * 0.0, PI * 0.80, 24, Color(1, 1, 1, 0.05), sh * 0.5, true)               # lower-right: a faint lit lip
	if down:
		draw_arc(c, fr - sh - r * 0.05, 0.0, TAU, RIM_SEGMENTS, Color(PUI.EMBER.r, PUI.EMBER.g, PUI.EMBER.b, 0.16), r * 0.08, true)

	# onboarding pulse: a single expanding ember ring
	if highlighted:
		var t: float = fmod(Time.get_ticks_msec() * 0.001, 1.2) / 1.2
		draw_arc(c, r * (1.05 + 0.30 * t), 0.0, TAU, RIM_SEGMENTS, Color(PUI.EMBER_BRIGHT.r, PUI.EMBER_BRIGHT.g, PUI.EMBER_BRIGHT.b, 1.0 - t), maxf(r * 0.07, 3.0), true)

	var icon_tint: Color = PUI.BONE_BRIGHT.lerp(PUI.EMBER_BRIGHT, 0.28) if down else (PUI.BONE_DIM if quiet else PUI.BONE)
	TouchIcons.draw_icon(self, icon_kind, c + Vector2(0.0, r * 0.03 if down else 0.0), fr * ICON_FRAC, icon_tint)

	if cooldown > 0.0:
		# Dark wedge over the face and an ember arc on the bezel, both shrinking as the cooldown runs out.
		var a0: float = -PI * 0.5
		var a1: float = a0 + TAU * clampf(cooldown, 0.0, 1.0)
		draw_arc(c, fr * 0.5, a0, a1, 32, Color(0.03, 0.02, 0.02, 0.62), fr, false)
		draw_arc(c, r - rw * 0.5, a0, a1, RIM_SEGMENTS, PUI.EMBER, rw * 0.7, true)

	if label != "":
		_draw_label(c, r)
	if badge != "":
		_draw_badge(c, r)


func _draw_label(c: Vector2, r: float) -> void:
	var font: Font = PUI.font("display_semi")
	var fs: int = int(maxf(r * 0.27, float(CAPTION_MIN_FS)))
	var key := "%s|%d" % [label, fs]
	if key != _label_key:
		_label_key = key
		_label_size = font.get_string_size(label, HORIZONTAL_ALIGNMENT_LEFT, -1, fs)
	var pos: Vector2 = c + Vector2(-_label_size.x * 0.5, r + _label_size.y * 0.8)
	var col: Color = PUI.EMBER_BRIGHT if tier == Tier.CONTEXT else PUI.BONE_BRIGHT
	draw_string_outline(font, pos, label, HORIZONTAL_ALIGNMENT_LEFT, -1, fs, 6, Color(0.03, 0.02, 0.02, 0.92))
	draw_string(font, pos, label, HORIZONTAL_ALIGNMENT_LEFT, -1, fs, col)


func _draw_badge(c: Vector2, r: float) -> void:
	var font: Font = PUI.font("display_bold")
	var br: float = r * 0.26
	var bp: Vector2 = c + Vector2(r * 0.62, -r * 0.62)
	var key := "%s|%.1f" % [badge, r]
	if key != _badge_key:
		_badge_key = key
		var fs: int = int(maxf(r * 0.30, 14.0))
		var ts: Vector2 = font.get_string_size(badge, HORIZONTAL_ALIGNMENT_LEFT, -1, fs)
		if ts.x > br * 1.7:   # long counts shrink to stay inside the plate
			fs = maxi(int(float(fs) * br * 1.7 / ts.x), 9)
			ts = font.get_string_size(badge, HORIZONTAL_ALIGNMENT_LEFT, -1, fs)
		_badge_fs = fs
		_badge_size = ts
	draw_circle(bp, br + 1.5, Color(0, 0, 0, 0.45))
	draw_circle(bp, br, PUI.IRON_DEEP)
	draw_arc(bp, br - 1.0, 0.0, TAU, 28, PUI.EMBER, 2.0, true)
	var base: Vector2 = bp + Vector2(-_badge_size.x * 0.5, (font.get_ascent(_badge_fs) - font.get_descent(_badge_fs)) * 0.5)
	draw_string(font, base, badge, HORIZONTAL_ALIGNMENT_LEFT, -1, _badge_fs, PUI.BONE_BRIGHT)
